version: '{build}'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - develop
nuget:
  disable_publish_on_pr: true
build_script:
- ps: .\Build.ps1
test: off
environment:
  access_token:
    secure: mmyJ4D1hQ1K09r0IX7DWvoraru+RMLC3VgrGPAMMHRPMdcMY72TvGxRPe7IHUoGg
  git_email:
    secure: y6PBI5U1oZHlb4uI7JPYHKwyz7UdRr9VPVHRUtZ+oCI=	
on_success:
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git config --global user.email "$($env:git_email)"
  - git config --global user.name "Scott Sargent"
  - git config --global core.autocrlf true
  - git checkout develop
  - git add .
  - git commit -m "ci deploy"
  - git status
  - git push origin develop:release -f
  